{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["Linux"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dataReceivedInErrorState"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":", "},{"kind":"typeIdentifier","identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOCore\/ByteBuffer","preciseIdentifier":"s:7NIOCore10ByteBufferV","text":"ByteBuffer"},{"kind":"text","text":")"}]}]}],"metadata":{"roleHeading":"Case","externalID":"s:7NIOCore25ByteToMessageDecoderErrorO014dataReceivedInF5StateyACs0F0_p_AA0B6BufferVtcACmF","symbolKind":"case","modules":[{"name":"NIOCore"}],"title":"ByteToMessageDecoderError.dataReceivedInErrorState(_:_:)","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dataReceivedInErrorState"},{"kind":"text","text":"("},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":", "},{"preciseIdentifier":"s:7NIOCore10ByteBufferV","kind":"typeIdentifier","text":"ByteBuffer"},{"kind":"text","text":")"}]},"sections":[],"variants":[{"paths":["\/documentation\/niocore\/bytetomessagedecodererror\/datareceivedinerrorstate(_:_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOCore","doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOCore\/ByteToMessageDecoderError"]]},"abstract":[{"text":"More data has been received by a ","type":"text"},{"code":"ByteToMessageHandler","type":"codeVoice"},{"text":" despite the fact that an error has previously been","type":"text"},{"text":" ","type":"text"},{"text":"emitted. The associated ","type":"text"},{"code":"Error","type":"codeVoice"},{"text":" is the error previously emitted and the ","type":"text"},{"code":"ByteBuffer","type":"codeVoice"},{"text":" is the extra data that has","type":"text"},{"text":" ","type":"text"},{"text":"been received. The common cause for this error to be emitted is the user not having torn down the ","type":"text"},{"code":"Channel","type":"codeVoice"},{"text":" ","type":"text"},{"text":"after previously an ","type":"text"},{"type":"codeVoice","code":"Error"},{"text":" has been sent through the pipeline using ","type":"text"},{"type":"codeVoice","code":"fireErrorCaught"},{"text":".","type":"text"}],"kind":"symbol","identifier":{"url":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOCore\/ByteToMessageDecoderError\/dataReceivedInErrorState(_:_:)","interfaceLanguage":"swift"},"references":{"doc://co.pointfree.VaporRouting/documentation/NIOCore/ByteToMessageDecoderError/dataReceivedInErrorState(_:_:)":{"title":"ByteToMessageDecoderError.dataReceivedInErrorState(_:_:)","url":"\/documentation\/niocore\/bytetomessagedecodererror\/datareceivedinerrorstate(_:_:)","type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dataReceivedInErrorState","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"ByteBuffer","preciseIdentifier":"s:7NIOCore10ByteBufferV","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"text":"More data has been received by a ","type":"text"},{"code":"ByteToMessageHandler","type":"codeVoice"},{"text":" despite the fact that an error has previously been","type":"text"},{"text":" ","type":"text"},{"text":"emitted. The associated ","type":"text"},{"code":"Error","type":"codeVoice"},{"text":" is the error previously emitted and the ","type":"text"},{"code":"ByteBuffer","type":"codeVoice"},{"text":" is the extra data that has","type":"text"},{"text":" ","type":"text"},{"text":"been received. The common cause for this error to be emitted is the user not having torn down the ","type":"text"},{"code":"Channel","type":"codeVoice"},{"text":" ","type":"text"},{"text":"after previously an ","type":"text"},{"code":"Error","type":"codeVoice"},{"text":" has been sent through the pipeline using ","type":"text"},{"code":"fireErrorCaught","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol","identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOCore\/ByteToMessageDecoderError\/dataReceivedInErrorState(_:_:)"},"doc://co.pointfree.VaporRouting/documentation/NIOCore/ByteToMessageDecoderError":{"type":"topic","role":"symbol","url":"\/documentation\/niocore\/bytetomessagedecodererror","abstract":[{"text":"Common errors thrown by ","type":"text"},{"type":"codeVoice","code":"ByteToMessageDecoder"},{"text":"s.","type":"text"}],"navigatorTitle":[{"text":"ByteToMessageDecoderError","kind":"identifier"}],"identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOCore\/ByteToMessageDecoderError","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ByteToMessageDecoderError","kind":"identifier"}],"kind":"symbol","title":"ByteToMessageDecoderError"},"doc://co.pointfree.VaporRouting/documentation/NIOCore":{"title":"NIOCore","abstract":[],"identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOCore","type":"topic","role":"collection","url":"\/documentation\/niocore","kind":"symbol"},"doc://co.pointfree.VaporRouting/documentation/NIOCore/ByteBuffer":{"abstract":[{"code":"ByteBuffer","type":"codeVoice"},{"text":" stores contiguously allocated raw bytes. It is a random and sequential accessible sequence of zero or","type":"text"},{"text":" ","type":"text"},{"text":"more bytes (octets).","type":"text"}],"title":"ByteBuffer","url":"\/documentation\/niocore\/bytebuffer","type":"topic","identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOCore\/ByteBuffer","role":"symbol","navigatorTitle":[{"text":"ByteBuffer","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ByteBuffer","kind":"identifier"}],"kind":"symbol"}}}